variables:
  IMAGE_TAG: $CI_PROJECT_NAME:$CI_PIPELINE_ID 

stages:
  - test
  - build
  - deploy

run_tests:
  stage: test
  image: python:3.9-slim-buster
  before_script:
#    - echo "Hello, $GITLAB_USER_LOGIN !"
    - apt-get update && apt-get install make
  script:
    - make test

build_image:
  stage: build
  before_script:
#    - docker info
#    - docker version
    - echo -n $HARBOR_PASSWORD | docker login -u $HARBOR_USERNAME --password-stdin $HARBOR_URL
#    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  after_script:
    - docker logout $HARBOR_URL
  script:
    - docker build -t $IMAGE_TAG .
    - docker tag $IMAGE_TAG $HARBOR_HOST/$HARBOR_PROJECT/$IMAGE_TAG
    - docker push $HARBOR_HOST/$HARBOR_PROJECT/$IMAGE_TAG

dev_deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@172.22.201.134 "
        echo -n $HARBOR_PASSWORD | docker login -u $HARBOR_USERNAME --password-stdin $HARBOR_URL &&
        docker ps -aq | xargs docker stop | xargs docker rm &&
        docker run -d -p 5000:5000 $HARBOR_HOST/$HARBOR_PROJECT/$IMAGE_TAG"
